version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/how-to-validate-names/app
    steps:
      - checkout:
          path: ~/how-to-validate-names
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
      docker:
        - image: circleci/node:12
      working_directory: ~/how-to-validate-names/app
      steps:
      - checkout:
          path: ~/how-to-validate-names
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Deploy Master Branch
          command: |
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "Deploying this project ..."
            echo $(git status)
            echo "Does this work?"
            echo "$FTP_ADDRESS"
            echo "{$process.env.FTP_ADDRESS}"
            git ftp init --init-if-not-exist --user "$FTP_USER" --passwd "$FTP_PASSWORD" $FTP_ADDRESS

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main