version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    parallelism: 1
    working_directory: ~/how-to-validate-names/app
    steps:
      - checkout:
          path: ~/how-to-validate-names
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist

  deploy:
    docker:
      - image: circleci/node:12
    parallelism: 1
    working_directory: ~/how-to-validate-names/app
    steps:
      - checkout:
          path: ~/how-to-validate-names
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          key: v1-pkg-cache
      # - run: go get -v github.com/bep/s3deploy
      # - save_cache:
      #     key: v1-pkg-cache
      #     paths:
      #       - /go/pkg
      # - run:
      #     name: Deploy to S3
      #     command: |
      #       s3deploy -source=dist/ -region=us-west-2 -bucket=rossta-connect-four

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master